
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Server.Models.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Data
{

    public int id { get; set; }

    public string fullname { get; set; }

    public string phone { get; set; }

    public string job { get; set; }

}

}
